### ISSUE TITLE
Demo not loading 

### ISSUE THREAD

**Issue by ArnavK-09** [Avaiga/demo-covid-dashboard#2]
15mins done

![Screenshot_2024-02-20-22-28-35-82_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/Avaiga/demo-covid-dashboard/assets/69188140/cb000ff1-c626-49ed-bab9-5e06d33972f4)

**Comment by FlorianJacta** [comment]
It should be live now
